name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish FeatureSwitches NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/FeatureSwitches/FeatureSwitches.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish FeatureSwitches.MSTest NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/FeatureSwitches.MSTest/FeatureSwitches.MSTest.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish FeatureSwitches.ServiceCollection NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/FeatureSwitches.ServiceCollection/FeatureSwitches.ServiceCollection.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
